proxy:
  title: Test Server
  port: 8080 
  template-path: ./templates/test
 
  authentication: simple
  admin-groups: admingroup
  users:
  - name: admin
    password: admin
    groups: admingroup
  
  container-backend: docker 
  
  docker:
      internal-networking: true
  
  specs:
  - id: testapp
    display-name: testapp
    description: testapp
    container-image: testapp
    container-network: sp-net
    access-groups: admingroup
    
  - id: euler
    display-name: Euler's number
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: openanalytics/shinyproxy-template
    access-groups: admingroup

    
logging:
  file:
    shinyproxy.log

 
