proxy:
  title: Test Server
  port: 8080 
  template-path: /templates/test
 
  authentication: none
  admin-groups: admingroup
  users:
  - name: admin
    password: admin
    groups: admingroup
  
  container-backend: docker 
  
  docker:
      internal-networking: true
  
  specs:
  - id: testapp
    display-name: Test app
    description: This is a shinyMobile app for testing PWA
    container-image: hstubbe/lcarsm:latest
    container-network: sp-net
    access-groups: admingroup

logging:
  file:
    shinyproxy.log

 
