# Use root/example as user/password credentials
version: '3.5'

services:
                              
  shinyproxy:
    # image: openanalytics/shinyproxy:latest
    image: shinyproxytest2
    ports:
      - 8080:8080
    networks:
      - sp-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: ":${DOCKERID}"

networks:
  sp-net:
    external: true

