# Use root/example as user/password credentials
version: '3.5'

services:
                              
  shinyproxy:
    image: openanalytics/shinyproxy:latest
    ports:
      - 8080:8080
    networks:
      - sp-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager
    volumes:
      - ./application/application_test.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./templates/test/:/templates/test/
    user: ":${DOCKERID}"

networks:
  sp-net:
    external: true

